### ISSUE TITLE
运行loppo报错，[ERROR] cannot find your document source directory

### ISSUE THREAD

**Issue by olivercm** [ruanyf/loppo#10]
✔ INFO [21:42:55] - [BEGIN] build docs
✔ INFO [21:42:55] - [BEGIN] handle config file
✔ INFO [21:42:55] - [END] handle config file
✔ INFO [21:42:55] - [BEGIN] handle chapters file
✖ ERROR [21:42:55] - [ERROR] cannot find your document source directory

**Comment by olivercm** [comment]
✔ INFO [21:42:55] - [BEGIN] build docs
✔ INFO [21:42:55] - [BEGIN] handle config file
✔ INFO [21:42:55] - [END] handle config file
✔ INFO [21:42:55] - [BEGIN] handle chapters file
✖ ERROR [21:42:55] - [ERROR] cannot find your document source directory

**Comment by ruanyf** [comment]
运行 loppo 命令的目录里面，必须有 docs 子目录。
