### ISSUE TITLE
能否支持markdown绘制流程图

### ISSUE THREAD

**Issue by koy1619** [ruanyf/loppo#12]
老师好 ！

能否支持markdown绘制流程图

流程图 #
序列图 #
甘特图 #

**Comment by ruanyf** [comment]
可以的，加入对 mermaid.js 的支持。https://github.com/knsv/mermaid

这周有时间，就做一下。

**Comment by ruanyf** [comment]
已经支持了。语法如下。

<pre>
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
</pre>

使用方法。

第一步，重装 loppo。

```bash
$ npm uninstall -g loppo
$ npm install -g loppo
```

第二步，删除文档项目中的`themes`目录。

第三步，重新生成文档。

```bash
$ loppo
```
