### ISSUE TITLE
删除chapters.yml

### ISSUE THREAD

**Issue by orangeyts** [ruanyf/loppo#17]
运行loppo的时候，是不是可以自动删除chapters.yml文件，
否则不会重新生成 目录文件。

**Comment by ruanyf** [comment]
`chapters.yml`不可以删。因为编排目录需要手动来做，软件没法自己琢磨出目录结构。

**Comment by orangeyts** [comment]
那我把chapters.yml删除了， 不是也自动生成这个文件了么？

**Comment by ruanyf** [comment]
软件是按文件名排序的。大多数情况下，目录结构应该独立于文件名。
