### ISSUE TITLE
when directory is too deep,UI is not right.I Think it‘s bug

### ISSUE THREAD

**Issue by lijiaoshou** [ruanyf/loppo#20]
Dear ryf，Thank you for your nice work.When I learn and use your loppo component,I find that when put directory too deep,UI is not right.For Example,directories like this:
chapters.yml:
- test/: test
- test/etst.md: etst.md
- devlelop/: devlelop
- devlelop/front/: front
- devlelop/front/1.md: 1.md
- devlelop/front/2.md: 2.md
- devlelop/back/: back
- devlelop/back/3/: 3
- devlelop/back/3/3.md: 3
- devlelop/back/4/4.md: 4
- other/: other
- other/etst.md: etst.md
you will find it is wrong.
I modified the lib/utils.js:
1.  i<(current_level-level);    -------------------->isFirstLevelDir?i<=(current_level-level):i<(current_level-level));
2.  level>current_level|| (level===current_level&&chapterPathOrigin.split('/')[level]==='')
----------------------> level>current_level|| (level===current_level&&chapterPathOrigin.split('/')[level]==='')||isFirstLevelDir

and then it worked~
Thanks your nice work again.

**Comment by ruanyf** [comment]
Thank you for the bug report.

I've already fixed it. Please try the latest version.

https://github.com/ruanyf/loppo/commit/065e679c71e40732691d242a40ff3d169aa857fe
