### ISSUE TITLE
为何只生成了page1.html ， page2.html？

### ISSUE THREAD

**Issue by luckypoem** [ruanyf/loppo#7]
hi.

root@localhost:/usr/local/loppo-site/docs# ls
page1.md  page2.md  page3.md  page4.md  page5.md
root@localhost:/usr/local/loppo-site/docs#
root@localhost:/usr/local/loppo-site/docs#  cd ../dist
root@localhost:/usr/local/loppo-site/dist# ls
assets  favicon.ico  index.html  page1.html  page2.html
root@localhost:/usr/local/loppo-site/dist# 

我创建了page1.md  page2.md  page3.md  page4.md  page5.md，为何只生成了page1.html ， page2.html？

**Comment by ruanyf** [comment]
你的 chapters.yml 是什么？

**Comment by luckypoem** [comment]
root@localhost:/usr/local/loppo-site# cat chapters.yml
- page1.md: 测试1
- page2.md: 测试2
root@localhost:/usr/local/loppo-site# 

难道每次都要手工修改 chapters.yml ？

**Comment by ruanyf** [comment]
是的。除了第一次，每次新增文件，都要手工改动 chapters.yml 。

因为没法判断文件之间的次序，以及哪些是草稿。

**Comment by luckypoem** [comment]
能做到分页吗

**Comment by ruanyf** [comment]
技术上能做到，但是不在计划之中。

**Comment by luckypoem** [comment]
要是作为一个博客程序，还是分页更好。楼主有空还是搞搞吧

**Comment by ruanyf** [comment]
博客生成器有好多可选的，这个就是文档生成器。
